### ISSUE TITLE
Вынести код, отвечающий за работу с элементов списка FinancialList в отдельный компонент

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#10]
https://github.com/aromanof/FinancialInspector/blob/53fa28b5b1a695f27e41e81c79f72b2d31643d3c/src/app/expense-list/expense-list.component.html#L5

Создать компонент FinancialListRecord. Данные передавать внутрь через @Input

**Comment by aromanof** [comment]
Input и Output позволяют шарить данные только между родительскими и дочерними компонентами, насколько я читал, а у меня таких нет. Поправь, если не прав

**Comment by MikeKovetsky** [comment]
позволяют шарить данные только между родительскими и дочерними компонентами - верно.
У меня таких нет - верно.

Поэтому давай создадим первый! Например, компонент, который будет отвечать за строку в financialList. financialListRecord может

**Comment by aromanof** [comment]
Seems like done. Check financial-list-component
