### ISSUE TITLE
Переписать формы на тег <form>

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#12]
https://github.com/aromanof/FinancialInspector/blob/1dae3027654387863e0c9932fcaabf4bd397bca3/src/app/add-expense/add-expense.component.html#L10

Буржуи любят нажимать enter для отправки формы, этого можно достичь, используя тег `<form (ngSubmit)=addItem(currentSign)>`
Все инпуты должны быть вложены в форму.

**Comment by aromanof** [comment]
Done
