### ISSUE TITLE
Переписать формы на FormGroup

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#13]
https://github.com/aromanof/FinancialInspector/blob/1dae3027654387863e0c9932fcaabf4bd397bca3/src/app/add-expense/add-expense.component.ts#L13

Сейчас модно использовать для форм не [(ngModel)], а FormControl. А FormBuilder для форм.
https://angular.io/api/forms/FormBuilder
Плюсы:
1) Они хорошо совместимы с rxjs.
2) Вместо 
`let objToPush = {
        name: this.description,
        value: this.value
      }`
Можно будет написать 
`let objToPush = this.newItemForm.value`
3) Вместо 
`if (this.value != null && this.description != "")`
Можно написать `if (this.newItemForm.valid)`
4) description и value собраны в один объект, что чуть удобней. 
Лучше 1 объект, чем 2 примитива. Пруф: https://refactoring.guru/ru/smells/primitive-obsession

**Comment by MikeKovetsky** [comment]
Когда поля 2 - не так больно. Когда больше или есть вложенности - появятся вопросы

**Comment by aromanof** [comment]
Looks like done to me, pls check, when you have free time
