### ISSUE TITLE
Вынести алгоритм поиска суммы в отдельный метод

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#14]
https://github.com/aromanof/FinancialInspector/blob/1dae3027654387863e0c9932fcaabf4bd397bca3/src/app/header/header.component.ts#L31

Вынести код 
`
let res: number = 0;
res += this.expensesList.reduce(function(total, el) // вместо  this.expensesList будет аргумент
{ return total + el.value}, 0);
return res;
`
в отдельный приватный метод `getSum(list: {value: number}): number` и переиспользовать его.

**Comment by aromanof** [comment]
Вроде все сделал как надо, ругается на аргумент, он внутрь попадает undefined, не пойму в чем дело.

**Comment by MikeKovetsky** [comment]
Какой именно аргумент? list?

**Comment by aromanof** [comment]
Уже все путём, сейчас залью ласт версию

**Comment by MikeKovetsky** [comment]
Можно упростить до 
```
private getSum(list: FinancialListRecord[]): number{
    return list.reduce(function(total, el)
    { return total + el.value}, 0);
  }
```

**Comment by aromanof** [comment]
```
private getSum(list: FinancialListRecord[]): number{
    return list.reduce((total, el) =>
    total + el.value, 0);
  }

```
Better?
