### ISSUE TITLE
Сменить название аргумента

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#17]
https://github.com/aromanof/FinancialInspector/blob/1dae3027654387863e0c9932fcaabf4bd397bca3/src/app/add-expense/add-expense.component.ts#L24

str - на втором месте по словам-паразитам после data. Вместе с value, obj, item (это еще норм)

Имена переменных должны описывать не тип данных это переменной, а называть сами данные бизнес-логики

**Comment by aromanof** [comment]
Done
