### ISSUE TITLE
Создание переиспользуемого типа для DataService

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#2]
https://github.com/aromanof/FinancialInspector/blob/53fa28b5b1a695f27e41e81c79f72b2d31643d3c/src/app/data.service.ts#L8

Вместо копипаста типа { name: string, value: number }, лучше создать отдельный тип 
```
export interface FinancialListRecord {
name: string;
value: number;
}
```

Для удобной работы можно создать доп тип для всего списка
`export type FinancialList = FinancialListRecord[];`

В дальнейшем объявление BehaviourSubject может принимать вид
`private incomeList = new BehaviorSubject<FinancialList>([]);`

**Comment by aromanof** [comment]
Interface created
