### ISSUE TITLE
[RESEARCH] Мультиязычность

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#22]
https://angular.io/guide/i18n - офф решение.
Так как оно не многим не нравится, можно рассмотреть https://medium.com/letsboot/translate-angular-4-apps-with-ngx-translate-83302fb6c10d

**Comment by aromanof** [comment]
Done

**Comment by MikeKovetsky** [comment]
Красиво! Можно, кстати вместо 
<span>{{'skyfall' | translate}}</span> 
Писать 
<span directive>skyfall</span> 
Так чуть компактней и без усатых скобок
