### ISSUE TITLE
Строгая типизация сигнатуры checkIncome

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#3]
https://github.com/aromanof/FinancialInspector/blob/53fa28b5b1a695f27e41e81c79f72b2d31643d3c/src/app/data.service.ts#L14

Большинство параметров методов нуждаются в строгой типизации для улучшение отлова ошибок на этапе компиляции

Предлагаю такой вариант

```
checkIncome(newIncomeList: FinancialList) {
    this.incomeList.next(newIncomeList);
  }
```

Объявление FinancialList можно подсмотреть в https://github.com/aromanof/FinancialInspector/issues/2

**Comment by MikeKovetsky** [comment]
По стандарту аргумент принимате тип `any`, что негативно сказывается на типизации. И в дальнейшем могут возникнуть неприятные ошибки, когда случайно туда залетит объект вместо списка. Либо вообще дата какая-нибудь

**Comment by aromanof** [comment]
Done
