### ISSUE TITLE
Вынести логику получения incomeList и expenseList в сервисы

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#5]
https://github.com/aromanof/FinancialInspector/blob/53fa28b5b1a695f27e41e81c79f72b2d31643d3c/src/app/header/header.component.ts#L15

Предлагаю вынести `JSON.parse(localStorage.getItem('incomeList')))` и аналоги в соответствующие сервисы. Компонент по определению не должен знать об источнике данных(локал сторадж), только о самих данных.
В будущем, если решишь переписать источник данных (на бекенд например), ты исправишь это в одном сервисе, а не во всех компонентах

**Comment by aromanof** [comment]
Вынесено в сервис data.service. Очевидно моё решение не наилучшее(смотри constructor в data.service.ts).

**Comment by MikeKovetsky** [comment]
Так лучше. Но основной посыл чуть другой. в компоненте Хедера не должны быть не слова о локалсторадже. Это все должно быть спрятано внутри сервиса. Сервис решает, откуда брать данные.

**Comment by MikeKovetsky** [comment]
Сори, не умею пользоваться гитхабом
