### ISSUE TITLE
Перенести обновление localStorage в сервис

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#6]
https://github.com/aromanof/FinancialInspector/blob/53fa28b5b1a695f27e41e81c79f72b2d31643d3c/src/app/expense-list/expense-list.component.ts#L29

На строке 28 вызывается команда 
`localStorage.setItem('expenseList', JSON.stringify(this.expensesList));`
Сразу после нее` this.data.checkExpenses(this.expensesList);`

Скорее всего localStorage обновляться должен в рамках метода `this.data.checkExpenses`.
Возможна ситуация, когда одно хранилище обновишь, про второе забудешь и будет рассинхрон данных.

**Comment by aromanof** [comment]
Done
