### ISSUE TITLE
Логическая ошибка при удалении записи

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#7]
https://github.com/aromanof/FinancialInspector/blob/53fa28b5b1a695f27e41e81c79f72b2d31643d3c/src/app/expense-list/expense-list.component.ts#L25

```
if(name == 'incomeList'){
      this.incomeList.splice(index, 1);
      localStorage.setItem('incomeList', JSON.stringify(this.incomeList));
      console.log(this.incomeList);
      this.data.checkExpenses(this.incomeList);
    }
```

В теле условия `name == 'incomeList'` выполняется обновление `this.data.checkExpenses` вместо `this.data.checkIncome`

**Comment by aromanof** [comment]
Done
