### ISSUE TITLE
Удаление "Бесконечных" подписок 

### ISSUE THREAD

**Issue by MikeKovetsky** [aromanof/FinancialInspector#9]
https://github.com/aromanof/FinancialInspector/blob/78450f7588c1d5862d75e08d426977fa1fd39038/src/app/expense-list/expense-list.component.ts#L18

Вызов метода subscribe с кастомными сущностями (кастомным BehaviourSubject как пример) предполагает отписку.
Прочитай https://netbasal.com/when-to-unsubscribe-in-angular-d61c6b21bad3

**Comment by aromanof** [comment]
Seems like done, but I can't get how to check, if everithing is fine now.

**Comment by MikeKovetsky** [comment]
I can't get how to check, if everithing is fine now

one of the most annoying angular problems
